### ISSUE TITLE
Consider disabling intrusive primaryPart behaviors

### ISSUE THREAD

**Issue by benbrimeyer** [vocksel/prefabs#50]
This is a matter of portability and instrusivness:

Some creators may have existing models they wish to convert to prefabs. These models may have a crucial visible PrimaryPart already defined in their model. Instead of encouraging wrapping these models with an ancestor Model, it would be nice if the Transparency + CanCollide off behavior was a configuration set by the developer.

**Comment by vocksel** [comment]
I agree this would be a very healthy change for the plugin. The intrusiveness of how we handle PrimaryParts is completely my preference and would be much better as a config option

**Comment by vocksel** [comment]
I think I'm going to remove this behavior soon and I can reintroduce it as an option later if not having it bothers me. It's essentially just an optimization to my workflow as I prefer to have the PrimaryPart act as kind of a placement guide, rather than being a part of the model itself. It's not documented anywhere so currently this is just unexpected behavior to anyone except myself
